name: Hello World
description: Greet Someone
inputs:
  who-to-greet: 
    required: true
    default: world
outputs:
  random-number:
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: composite
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: chmod +x goodbye.sh
      shell: bash
    - run: goodbye.sh
      shell: bash
