name: test composite actions

on:
  push:

jobs:
  test-c-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: ls ./
      - run: pwd
      - uses: ./
        id: compoAct
        with:
          who-to-greet: tester
          number1: 2
          number2: 3
      - run: echo ${{ steps.compoAct.outputs.random-number }}
      - run: echo ${{ steps.compoAct.outputs.result }}
